[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
remappings = ["@oppenzeppelin/=lib/openzeppelin-contracts"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
